name: "auto submit"

on:
  schedule:
    - cron: "50 23 * * *"  # scheduled at 07:50 (UTC+8) everyday
  workflow_dispatch:

env:
  # auto merge from y1ndan/genshin-impact-helper, default: false
  ALLOW_MERGE: 'false'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-300 -n 1)

      - name: Run sign
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python3 yqxx/yqxx.py -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }} -c def_config.yml --gpsjd ${{ secrets.GPSJD }} \
            --gpswd ${{ secrets.GPSWD }} --kzl6 ${{ secrets.PROVINCE }} --kzl7 ${{ secrets.CITY }} --kzl8 ${{ secrets.DISTRICT }} \
            --kzl9 ${{ secrets.ADDRESS }} 
          
